### ISSUE TITLE
Getting warnings while trying to read rtsp url

### ISSUE THREAD

**Issue by Manideep08** [thehapyone/NanoCamera#6]
I am getting the below warnings while trying to use the library. I am using it on JetsonNX.

[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module rtspsrc4 reported: Could not open resource for reading and writing.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created

Any idea on resolving them

**Comment by thehapyone** [comment]
It seems this error is related to the streaming source. Can you attempt to use a third party to open the rtsp video stream and see if it works? You can use VLC or ffmpeg (https://trac.ffmpeg.org/wiki/StreamingGuide).
